version: "2"
services:
    plex:
        image: ghcr.io/linuxserver/plex
        container_name: plex
        network_mode: bridge
        privileged: true
        ports:
            - "32400:32400"
        environment:
            - PUID=1001 # for UserID - `id username` - Gets username if and group ids it is a part of.
            - PGID=1002 # for GroupID
            - VERSION=docker # Let Docker handle the Plex Version, we keep our Dockerhub Endpoint up to date with the latest public builds.
            - TZ=Europe/London
            - PLEX_CLAIM=claim-MrRfmeDz-rTiKL2F8zzu # https://plex.tv/claim - If you have not already claimed your server (first time setup) you need to set PLEX_CLAIM to claim a server set up with bridge networking
        volumes:
            - /media/bradleytenuta/TOSHIBA EXT/Movies:/movies
            - /media/bradleytenuta/TOSHIBA EXT/TV_Shows:/tv
        restart: unless-stopped
