version: "2"
services:
    plex:
        image: ghcr.io/linuxserver/plex
        container_name: plex
        network_mode: host
        environment:
            - PUID=1001 # for UserID - `id username` - Gets username if and group ids it is a part of.
            - PGID=1002 # for GroupID
            - VERSION=docker # Let Docker handle the Plex Version, we keep our Dockerhub Endpoint up to date with the latest public builds.
        volumes:
            - ~/piplex/config:/config
        #    - /path/to/tvseries:/tv
        #    - /path/to/movies:/movies
        restart: unless-stopped
